version: '3.8'

services:
  frontend:
    build:
      context: ./cabin_smart_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./cabin_smart_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cabin_smart_backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongodb:27017/cabin_smart
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cabin_smart
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
